
export default {
	FETCH_LOCATIONS_START: "FETCH_LOCATIONS_START",
	FETCH_LOCATIONS_BY_BOUNDS_START: "FETCH_LOCATIONS_BY_BOUNDS_START",
	FETCHING_LOCATIONS: "FETCHING_LOCATIONS",
	FETCHING_LISTING: "FETCHING_LISTING",
	FETCH_SUCCESS: "FETCH_SUCCESS",
	FETCH_FAILURE: "FETCH_FAILURE",
	CHANGE_HIGHLIGHT: "CHANGE_HIGHLIGHT",
	CHANGE_INFOBOX: "CHANGE_INFOBOX",
	CHANGE_SIZE: "CHANGE_SIZE",
	CHANGE_CENTER: "CHANGE_CENTER",
	CHANGE_PAGE: "CHANGE_PAGE"
};