
export default {
	FETCH_LOCATIONS_START: "FETCH_LOCATIONS_START",
	FETCH_LOCATIONS_BY_BOUNDS_START: "FETCH_LOCATIONS_BY_BOUNDS_START",
	FETCHING_LOCATIONS: "FETCHING_LOCATIONS",
	FETCHING_LISTING: "FETCHING_LISTING",
	FETCH_SUCCESS: "FETCH_SUCCESS",
	FETCH_FAILURE: "FETCH_FAILURE",
	FETCH_REVIEWS: "FETCH_REVIEWS",
	FETCHING_REVIEWS: "FETCHING_REVIEWS",
	FETCH_REVIEWS_SUCCESS: "FETCH_REVIEWS_SUCCESS",
	FETCHING_REVIEWS_FAILURE: "FETCHING_REVIEWS_FAILURE",
	CHANGE_HIGHLIGHT: "CHANGE_HIGHLIGHT",
	CHANGE_INFOBOX: "CHANGE_INFOBOX",
	CHANGE_SIZE: "CHANGE_SIZE",
	CHANGE_CENTER: "CHANGE_CENTER",
	CHANGE_PAGE: "CHANGE_PAGE",
	CHANGE_ROUTE: "CHANGE_ROUTE",
};